{
 "title": "Maerklin Homepage",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Current",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT timestamp_iso, CASE\n    WHEN state == \"go\" THEN 100\n    WHEN state == \"stop\" THEN 0\n    WHEN state == \"halt\" THEN 50\nEND AS state\nFROM system_state",
     "rawQueryText": "SELECT timestamp_iso, CASE\n    WHEN state == \"go\" THEN 100\n    WHEN state == \"stop\" THEN 0\n    WHEN state == \"halt\" THEN 50\nEND AS state\nFROM system_state",
     "timeColumns": [
      "time",
      "ts",
      "timestamp_iso"
     ]
    }
   ]
  },
  {
   "title": "Status Heatmap",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 4, "y": 1 },
   "targets": [
    {
     "queryText": "SELECT timestamp_iso, CASE\n    WHEN state == \"go\" THEN 100\n    WHEN state == \"stop\" THEN 0\n    WHEN state == \"halt\" THEN 50\nEND AS state\nFROM system_state",
     "rawQueryText": "SELECT timestamp_iso, CASE\n    WHEN state == \"go\" THEN 100\n    WHEN state == \"stop\" THEN 0\n    WHEN state == \"halt\" THEN 50\nEND AS state\nFROM system_state",
     "timeColumns": [
      "time",
      "ts",
      "timestamp_iso"
     ]
    }
   ]
  },
  { "title": "Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Config Updates",
   "type": "logs",
   "gridPos": { "h": 21, "w": 4, "x": 0, "y": 10 },
   "targets": [
    {
     "queryText": "SELECT timestamp_iso,config FROM config",
     "rawQueryText": "SELECT timestamp_iso,config FROM config",
     "timeColumns": [
      "time",
      "ts",
      "timestamp_iso"
     ]
    }
   ]
  },
  {
   "title": "Participant Ping",
   "type": "logs",
   "gridPos": { "h": 21, "w": 5, "x": 4, "y": 10 },
   "targets": [
    {
     "queryText": "SELECT * FROM participant_ping",
     "rawQueryText": "SELECT * FROM participant_ping",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "S88 Event",
   "type": "logs",
   "gridPos": { "h": 21, "w": 5, "x": 9, "y": 10 },
   "targets": [
    {
     "queryText": "SELECT timestamp_iso,contact_id,hash_value,response,device_id,state_old,state_new FROM s88_event",
     "rawQueryText": "SELECT timestamp_iso,contact_id,hash_value,response,device_id,state_old,state_new FROM s88_event",
     "timeColumns": [
      "time",
      "ts",
      "timestamp_iso"
     ]
    }
   ]
  }
 ]
}