{
 "title": "Loc LOC_ID",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  { "title": "Speed", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Current Speed",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT timestamp_iso, speed FROM locomotive_speed  WHERE loc_id = LOC_ID",
     "rawQueryText": "SELECT timestamp_iso, speed FROM locomotive_speed  WHERE loc_id = LOC_ID",
     "timeColumns": [
      "time",
      "ts",
      "timestamp_iso"
     ]
    }
   ]
  },
  {
   "title": "Speed",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 3, "y": 1 },
   "targets": [
    {
     "queryText": "SELECT timestamp_iso, speed FROM locomotive_speed WHERE loc_id = LOC_ID",
     "rawQueryText": "SELECT timestamp_iso, speed FROM locomotive_speed WHERE loc_id = LOC_ID",
     "timeColumns": [
      "time",
      "ts",
      "timestamp_iso"
     ]
    }
   ]
  },
  {
   "title": "Loc Direction",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT timestamp_iso, direction FROM locomotive_direction  WHERE loc_id = LOC_ID",
     "rawQueryText": "SELECT timestamp_iso, direction FROM locomotive_direction  WHERE loc_id = LOC_ID",
     "timeColumns": [
      "time",
      "ts",
      "timestamp_iso"
     ]
    }
   ]
  }
 ]
}